import React, { useEffect } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import { FastForwardIcon, PlayIcon } from '@heroicons/react/solid';
import { BiPlay } from 'react-icons/bi';

const Landing = () => {
  return (
    <div className='flex h-screen w-screen bg-neutral-900 items-center justify-center'>
      <Head>
        <title>Guess that song!</title>
        <meta
          name='description'
          content='Generated by create-t3-app'
        />
      </Head>
      <Link href='/guesspot/game'>
        <FastForwardIcon className='w-[35rem] cursor-pointer text-gray-200' />
      </Link>
      <div className='h-full w-1/2 flex items-end p-32 flex-col'>
        <h1 className='text-8xl font-bold text-green-600'>GUESSPOT</h1>
        <h2 className='text-7xl font-bold text-gray-200 text-right py-8 px-6'>
          Guess <br />
          the <br />
          song <br />
          and the <br />
          artist
        </h2>
      </div>
    </div>
  );
};

export default Landing;
